kind: pipeline
name: default

clone:
  depth: 1

steps:
  - name: publish
    image: plugins/docker
    settings:
      auto_tag: true
      dockerfile: Dockerfile
      tags:
        - latest
        - "5.20"
        - "5.20.2"
      password:
        from_secret: docker_password
      repo: node3030/docker-mattermost
      username:
        from_secret: docker_username
    when:
      event:
        - push
        - tag
